disabled_rules: # rule identifiers to exclude from running
 - identifier_name
 - void_return
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods
 - falconTests
 - falconUITests
 - vendor
 - fastlane
warning_threshold: 120
function_parameter_count:
  warning: 6
custom_rules:  
  avoid_legacy_currency_formatter_ussage:
    regex: "(LocaleAmountFormatter.string)"
    severity: error
    message: Use Currency.formattedString instead
  use_wrapped_error:
    regex: ^\s*throw (?!MuunError)
    severity: warning
    message: replace with throw MuunError(...)
